Glide integration
kbond/filesystem pull request #49
Opened 2022-08-17 10:59 UTC by Lustmored

Given the simplicity of features in this library I found it simple to add glide server integration. Given glide popularity I believe it is worth to be available out of the box.

It is implemented by `UrlBuilderGlideUrlFeature`, which takes Glide own `UrlBuilder` as an argument and uses it to generate URLs for images (with URL signing when configured and all that stuff).

Usage is as simple as calling `$image->glideUrl(['w' => 100, 'h' => 100])`.

2022-08-17 16:55 UTC, kbond commented
Excellent! Glide integration was indeed on my radar.

One thing I'd like to do is make this feature more generic. Here's what I'm thinking:

```php
namespace Zenstruck\Filesystem\Feature;

use Zenstruck\Filesystem\Node\File\Image;
use Zenstruck\Uri;

interface ImageTransformationUrl
{
    public function imageTransformationUrlFor(Image $file, mixed $options = []): Uri;
}
```

Then in `Zenstruck\Filesystem\Node\File\Image`, we'll add a generic `transformationUrl()` method.

My reasoning here is there are several implementations we could have:

1. Glide (this PR)
2. Route - some custom route that does your own thing (I use this in my app along with Imagine)
3. Cloudinary (cloud based image transformation service)
4. Imgix (similar to Cloudinary)

I wouldn't want to have a new `Image::*url()` for every implementation.

WDYT?

BTW, is _transformation_ the best term to use here?

2022-08-17 17:02 UTC, kbond commented
I'm not super familiar with Glide but one thing that I think we'd need as well is some kind of `Filesystem<->Glide` *bridge* to be able to use `Zenstruck\Filesystem`'s with glide. Not sure how this would work yet.

2022-08-18 09:23 UTC, Lustmored commented
> I'm not super familiar with Glide but one thing that I think we'd need as well is some kind of `Filesystem<->Glide` _bridge_ to be able to use `Zenstruck\Filesystem`'s with glide. Not sure how this would work yet.

I think we actually don't. Glide is already built on top of Flysystem and requires configuration by it's own. And when it's configured all that we need is an instance of `UrlBuilder` to work with it.

About making this feature more generic - I'm all in :D this is somehow on par with image manipulation interface I have in my mind right now (expect PR soon :wink: ).

And about the naming. I would love for this to be short, because long method names look weird in Twig templates to me. How about calling it "thumbnailers" and use `thumbUrl` on image class? Those transformators are way more powerful than just thumbnailing, yet this is the main usage for them.

2022-08-18 14:35 UTC, kbond commented
> I think we actually don't. Glide is already built on top of Flysystem and requires configuration by it's own. And when it's configured all that we need is an instance of UrlBuilder to work with it.

But this would require configuring flysystem twice, no? Once for glide and once for this library.

> And about the naming. I would love for this to be short, because long method names look weird in Twig templates to me. How about calling it "thumbnailers" and use thumbUrl on image class? Those transformators are way more powerful than just thumbnailing, yet this is the main usage for them.

I think I'd still like to call the feature interface `ImageTransformationUrl` or maybe `TransformImageUrl` then maybe `Image::transformUrl()` is a bit shorter? I'd be fine with a second alias method of `thumbUrl()` - you're right, it is the most common usage.

(naming stuff _well_ is an obsession of mine - maybe a sickness tbh...)

> I'm all in :D this is somehow on par with image manipulation interface I have in my mind right now

Did you take a look at #15? I'd really like to have this library able to transform the images itself (using Imagine or Intervention - they are the most popular libraries I think).

I was thinking something like:

```php
$image = $filesystem->image('some/image.png)
    ->transform(function(ImagineImage|IterventionImage $image): ImagineImage|IterventionImage {
        return $image->transformation1()->transformation2();
    })
;

$image; // ?? \SplFileInfo
```

My idea was this `transform()` method would return an `SplFileInfo` that can be written to a filesystem. @weaverryan expressed some concern that it could be unexpected that it return an `SplFileInfo` object and not manipulate the image in place on the filesystem. I agree but at the same time, I don't think we want to manipulate the _image in-place_... Or if we do, another method that does that. We'd want a way to create multiple *manipulated images* from a base image.

2022-08-19 10:01 UTC, Lustmored commented
I have made changes to the feature and classes names as suggested. Hopefully they are generic enough right now :) I didn't change Sf bridge configuration for now as I'm unsure on how to get this right, so input welcome :)

> But this would require configuring flysystem twice, no? Once for glide and once for this library.

The way I see using this lib, flysystem and glide it does not, but maybe I'm missing something. I see all of those working in a tandem like this:
- Flysystem is integrated in the project by [flysystem-bundle](https://packagist.org/packages/league/flysystem-bundle) and this is where all flysystem-specific configuration goes (maybe we should add it to suggested in composer for better Symfony integration?)
- Glide is configured in an endpoint (regular Sf controller) that auto-wires required Flysystem adapters by the bundle and configures Glide as desired.
- Glide own `UrlBuilder` needs minimal setup (which most projects probably do already), like this one:
```
$services->set(UrlBuilder::class)
             ->factory([UrlBuilderFactory::class, 'create'])
             ->arg('$baseUrl', 'https://%domain.img%/')
    ;
```
- This library configures filesystems based on adapters already configured by `flysystem-bundle`.

2022-08-19 15:52 UTC, kbond commented
> This library configures filesystems based on adapters already configured by flysystem-bundle.

Ah, ok, I understand now. My intention was to have this library/bundle as an alternative to `flysystem-bundle` but didn't like that it was required to choose *one or the other*.

That being said, this bundle can be used standalone but I will look into how we can better integrate with flysystem-bundle (#53).

2022-08-19 16:12 UTC, kbond requested changes
Looks good! Just a few minor things.

2022-08-19 16:12 UTC, kbond commented on src/Filesystem/Feature/TransformImageUrl/GlideTransformImageUrl.php
> +        return Uri::new($this->urlBuilder->getUrl($image->path(), $options));
What do you think about this:

```suggestion
        $options = match(true) {
            \is_string($options) => ['p' => $options], // is glide "preset"
            \is_array($options) && !is_array_list($options) => $options, // is standard glide parameters
            \is_array($options) => ['p' => \implode(',', $options)], // is array of "presets"
            default => throw new \LogicException('invalid options... todo'),
        }

        return Uri::new($this->urlBuilder->getUrl($image->path(), $options));
```

This gives the ability to use [Glide presets](https://glide.thephpleague.com/1.0/config/defaults-and-presets/) easily.

Both Imagine and Intervention have the concept of _filters_ which you can use to name and wrap _multiple_ manipulations. The reason I chose `mixed $options` was to make it easier to pass a single string (the filter) to `Image::transformUrl()`: `$image->transformUrl('square_200')`.

2022-08-19 16:27 UTC, kbond commented
> I have made changes to the feature and classes names as suggested. Hopefully they are generic enough right now :) I didn't change Sf bridge configuration for now as I'm unsure on how to get this right, so input welcome :)

I think the current configuration is fine, assuming we have good integration with flysystem-bundle. I do still think there should be a possibility of using this bundle and glide standalone. Something like:

```yaml
zenstruck_filesystem:
    filesystems:
        images: 'some.dsn'
        glide.cache: 'some.dsn'

    glide_server:
        source: images # filesystem name from above
        cache: glide.cache # filesystem name from above
        # ... other ServerFactory options
```

Basically create the [`ServerFactory`](https://glide.thephpleague.com/2.0/config/setup/) service Maybe this live.

But I'll save this for later.

2022-08-19 16:30 UTC, kbond commented
BTW, don't worry about getting bogged down fixing failing sca/cs jobs. Tests pass so that's fine.

2022-08-19 17:08 UTC, kbond commented on README.md
> +$url = $file->thumbUrl(['w' => 100, 'h' => 100]);
```suggestion
// If your filesystem supports transforming urls with a set of parameters
$url = $file->transformUrl(['w' => 100, 'h' => 100]); // Zenstruck\Uri
(string) $url; // string (ie https://example.com/glide/image.png?w=100&h=100)

// If your filesystem supports transforming urls with a set of parameters
$url = $file->transformUrl('square-100'); // Zenstruck\Uri
(string) $url; // string (ie https://example.com/glide/image.png?p=square-200)

// You can also use shorter alias
$url = $file->thumbUrl(['w' => 100, 'h' => 100]);
```

2022-08-19 17:11 UTC, kbond commented on README.md
> +(string) $filesystem->image('some/image.png')->transformUrl(['w' => 100, 'h' => 100]); // "/glide/some/image.png?w=100&h=100&s=3a82607a9517525d0a98de4548e10917"
```suggestion
// generate with Glide manipulation options
(string) $filesystem->image('some/image.png')->transformUrl(['w' => 100, 'h' => 100]); // "/glide/some/image.png?w=100&h=100&s=3a82607a9517525d0a98de4548e10917"

// generate with a Glide preset
(string) $filesystem->image('some/image.png')->transformUrl('square-100'); // "/glide/some/image.png?p=square-100&s=3a82607a9517525d0a98de4548e10917"

// generate with multiple Glide presets
(string) $filesystem->image('some/image.png')->transformUrl(['square-100', 'low-quality']); // "/glide/some/image.png?p=square-100,low-quality&s=3a82607a9517525d0a98de4548e10917"
```

2022-08-29 20:09 UTC, kbond commented
Let's drop the wiring in the Symfony bundle for now. Once we have more implementations of this feature available, we can re-evaluate how it should be configured.

My plan is to have a `features` config for each filesystem to add whatever you want and act as an escape hatch for adding this without an explicit config option:

```yaml
zenstruck_filesystem:
    filesystems:
        public:
            dsn: ...
            features:
                Zenstruck\Filesystem\Feature\TransformImageUrl: some.service
```

2022-09-14 11:23 UTC, Lustmored commented
I am closing this in favor of #79

2022-09-14 11:23 UTC, closed without merging