POC for image transformer
kbond/filesystem pull request #52
Opened 2022-08-19 09:50 UTC by Lustmored

This is more proof of a concept than actual implementation. I had a bit different approach to image manipulation that I wanted to explore.

The idea is to be able to use any transformer desired in a simple, Closure-based API (somehow like #15 but in a more generic way):

```
/** @var Image $image */
$image->transform()
    ->usingGD(function(GdImage $gd) {
        // Manipulate image
        return $gd;
    })
    // OR
    ->usingImagick(function(Imagick $imagick) {
        // Manipulate image
        return $imagick;
    })
    // OR
    ->usingIntervention(function(\Intervention\Image\Image $image){
        // Manipulate image
        return $image;
    })
    // OR possible others
    
    // Save resulting image
    ->overwrite()
    // OR
    ->saveAs('image.png')
;
```

Both `overwrite` and `saveAs` return `Image`, so we stay within this library objects through the whole process and only use underlying resources/classes in passed closures.

It would allow us to provide wrappers for as many libraries/extensions (VIPS/Imagine etc.) with ease by implementing just 2 methods for each (defined in `Driver` class):
- one that takes the `Image` and returns resource or object associated with the driver
- one that takes the resource or object associated with the driver and returns image string or stream to be saved

As it currently stands there are some DI problems I've encountered, but probably nothing that can't be overcome. Especially given `ImageTransform` object is created within `Image` context, but would benefit greatly from access to the `MultiFilesystem` (to ease taking for example an image from temp filesystem, manipulate it and store in the other).

For now I'd love to hear what do you think about this approach as is it worth investing more time in it? :)

2022-08-19 18:31 UTC, kbond commented
I really like this! Solves what to do after the image has been manipulated nicely.

> Both overwrite and saveAs return Image, so we stay within this library objects through the whole process and only use underlying resources/classes in passed closures.

This is what solves my above dilemma. So:

1. `->overwrite()` saves the image in place on the current filesystem?
2. `->saveAs('/some/path.png')` saves it to a new path in the current filesystem? I think what you're getting at later in your description would be a way to use `image-cache://some/path.png` as the path to save to a different filesystem?

What do you think about another method: `->file()` that returns a `PendingFile` object that can then be easily written to another filesystem instance (#54 will make this easier).

I do have another library: [zenstruck/callback](https://github.com/zenstruck/callback) that makes it easy to detect a callable's typehint and inject the correct object. This could make this feature very extensible:

```php
$image->transform()
    ->using(function(ImagineImage $image) {}) // or
    ->using(function(InterventionImage $image) {}) // or
    ->using(function(GdImage $image) {}) // or
    ->using(function(ImagickImage $image) {}) // or
    ->using(function(SomethingWeDontSupportOutOfTheBoxImage $image) {})
;
```

I think this would also open the possibility to alternatively manipulate a file in-place using `Filesystem::write()` (currently only works for SplFileInfo objects):

```php
$filesystem->write('some/existing/image.png', function(GdImage $image) {
    // some manipulations
    return $image;
}); // overwrites 'some/existing/image.png' with the manipulated one
```

2022-08-19 19:07 UTC, kbond requested changes
Few suggested changes.

BTW, don't worry about `zenstruck/callback` integration for a single `->using()` method. It's usage is a bit complicated and I have yet to write docs for it. Keep the `usingX()` methods as you have now. I can create a follow-up PR to experiment with my idea.

2022-08-19 19:07 UTC, kbond commented on src/Filesystem/ImageTransformer/Driver.php
> +    public function getContents(mixed $resource): mixed;
I don't believe this method is actually used anywhere.

2022-08-19 20:07 UTC, kbond commented on src/Filesystem/Node/File/Image.php
> +    final public function transform(): ImageTransformer
Will need a way to make the image transformer lazy for the bundle if we go this route. Wouldn't want Imagine/Intervention instantiated everytime you use the filesystem.

2022-08-19 20:18 UTC, kbond commented
One problem I just thought of: this bypasses the `ReadonlyFilesystem` protection as it uses the underlying adapter directly.

2022-08-20 07:17 UTC, Lustmored commented on src/Filesystem/ImageTransformer/ImageTransformer.php
> +        $this->ensureUnset();
I really love that idea! I had a problem there with separation of concerns in design, but that simple idea will definitely be more readable.

2022-08-20 07:18 UTC, Lustmored commented on src/Filesystem/ImageTransformer/ImageTransformer.php
> +    public function __construct(
Right - going along those lines will allow for DI where needed, so definitely something to do 👍

2022-08-20 07:20 UTC, Lustmored commented on src/Filesystem/Node/File/Image.php
> +    final public function transform(): ImageTransformer
Something like that, but I'd create another `ImageTransformerFactory` that would be passed - we need to create a new `ImageTransformer` class for each new image to be transformed. And that factory can definitely be lazy 👍

2022-08-20 07:23 UTC, Lustmored commented on src/Filesystem/ImageTransformer/Driver.php
> +    public function getContents(mixed $resource): mixed;
My bad - it should be called in `transform()` on the result from the closure. Good catch 👍

2022-08-20 07:26 UTC, Lustmored commented
> One problem I just thought of: this bypasses the `ReadonlyFilesystem` protection as it uses the underlying adapter directly.

Right - I would love to use `Filesystem` class in there (and not the underlying adapter) - it would even simplify write method, but as it is right now there was no way to pass `Filesystem`. But when I will change `ImageTransform` instantiation to lazy factory (per comments) we can inject MultiFilesystem there to get what is needed to do this right.

Thank you for very fruitful review. I might have less time during next week to work upon it, but will definitely come back to push it further.

2022-08-21 18:20 UTC, kbond commented
> Right - I would love to use Filesystem class in there (and not the underlying adapter) - it would even simplify write method, but

I think this is going to be a technical challenge, we can't just pass the the `AdapterFilesystem `when creating the `Operator `because it might not be the top-level Filesystem used (ie it's wrapped in a `ReadonlyFilesystem`).

Injecting a `MultiFilesystem `could work but I think that make's it harder to use _standalone_ (without the bundle).

I'm thinking we should have a _rule_ that `Node`'s cannot ever _manipulate_ themselves. Any write operations must be done using a `Filesystem`. This rule means `$file->setContents('foo')` is not allowed but also `$image->manipulate(fn(\GDImage $i) => ...)->overwrite()|saveAs()`.

So, for how to copy/overwrite a manipulated image:

```php
$pendingFile = $filesystem->image('some/image.png')->manipulate(fn(\GDImage $i) => ...);

$filesystem->write('new/image.png', $pendingFile); // to create a new image
$filesystem->write('some/image.png', $pendingFile); // to overwrite
```

That's a bit verbose but I think it's pretty explicit. I'm thinking we can have some helpers though:

```php
// overwrite
$filesystem->write('some/image.png', fn(\GDImage $i) = ...);

// "save as"
$filesystem->copy('some/image.png', 'new/image.png', ['transform' => fn(\GDImage $i) = ...]);

// "save as is a little verbose, so maybe we can pass the callable directly to Filesystem::copy()'s $options
$filesystem->copy('some/image.png', 'new/image.png', fn(\GDImage $i) = ...);
```

I've explored my idea in #56. I don't mean to invalidate this proposal, I just got excited about this feature! 😄

2022-09-02 13:19 UTC, kbond commented
Closing in favor of #56, thanks for the inspiration!

2022-09-02 13:19 UTC, closed without merging